### ISSUE TITLE
Add an option to automatically disable AutoPlay

### ISSUE THREAD

**Issue by lawrencehook** [lawrencehook/remove-youtube-suggestions#33]

**Comment by ubaifadhli** [comment]
I'm still inexperienced with CSS selector nor JS, but I think this can be achieved by : 
- hiding `button[class=ytp-button]`
- changing `div.ytp-autonav-toggle-button`'s `aria-checked` value to false. not pretty sure but I think this needs a conditional in the code because of the attribute value change

What do you think? I can try creating a pull request if this is an okay idea.

**Comment by lawrencehook** [comment]
Thanks for investigating! Feel free to give it a shot if you'd like. Head's up I agree that it might be a bit tricky because this option will be different from the existing ones because the JavaScript involved.

**Comment by lawrencehook** [comment]
Possible approach: add a mutation observer and click on the result of `document.querySelectorAll(".ytp-autonav-toggle-button[aria-checked='true']")` if it exists.

**Comment by lawrencehook** [comment]
```
Array.from(document.querySelectorAll(".ytp-autonav-toggle-button[aria-checked='true']")).forEach(e => e.click())
```

**Comment by lawrencehook** [comment]
done as of 402d6cab25ca3c76dcafbcbd074cfda4d1c050ed
