### ISSUE TITLE
Homepage/Search suggestions appear when they shouldn't.

### ISSUE THREAD

**Issue by bluelightzero** [lawrencehook/remove-youtube-suggestions#64]
Refreshing the page fixes the issue, but navigating around youtube breaks it.

I'm guessing the new layout is the cause.

**Comment by lawrencehook** [comment]
Hi @bluelightzero, thanks for making the issue.

Are you using Chrome or Firefox?

**Comment by bluelightzero** [comment]
Firefox

**Comment by pasi123567** [comment]
I just wanted to open a similar issue myself and then saw this. I noticed that search suggestions (for you, people have also seen etc.) showed up when I started searching for something from my subscriptions tab. This didn't happen when starting from the homepage. I don't know if this is a new layout related issue since I just installed this addon for the first time.
Seems that boith chrome and firefox are affected though.

**Comment by lawrencehook** [comment]
I think I found the problem. Hopefully it's fixed as of version 4.3.14.

Just released to Firefox.
The update to Chrome will take more time. I'm still waiting on them to approve a change from last week.

**Comment by pasi123567** [comment]
Works perfectly on my end now👍 Thanks a lot

**Comment by lawrencehook** [comment]
deployed!
