### ISSUE TITLE
FEATURE REQUEST : Require Challenge for changing settings

### ISSUE THREAD

**Issue by bhavyaw** [lawrencehook/remove-youtube-suggestions#66]
Thanks for creating this amazing extension!!

Currently its very simple to toggle settings. I would prefer if there was some sort of Challenge before changing the settings. Its there in some other apps as well like StayFocusd Chrome extension. 

It would add another layer of friction point b/w user and the content.

1. Require Challenge can be enabled for a particular setting or any given setting.
2. Require challenge can be  : 
    - Simple Puzzle
    - Math Problem
    - Copy writing small paragraph word to word ( as in Stay Focusd extension ) without using backspace

**Comment by theAkito** [comment]
> I am slightly addicted to youtube tbh and would prefer if there was some sort of Challenge before changing the settings.

While this request as a feature request is not particularly invalid, I suppose adding it wouldn't change much about your internal thought process leading to your behaviour.

If you truly want to get off the problem, you need to make your brain understand how YouTube is actually a huge pile of shit.
Once you get that, you will stop having the urge to get sucked into the brainwashing machine YouTube is & you will neither need any challenge, nor force yourself to not look at suggestions, because you simply won't want to, in the first place.

If you are truly interested in fixing the root of the issue, I suggest you research how YouTube works, what it does, what the point of it is and, most importantly, how it evolved backward in the past 15 years.

**Comment by bhavyaw** [comment]
@theAkito,


> > I am slightly addicted to youtube tbh and would prefer if there was some sort of Challenge before changing the settings.
> 
> While this request as a feature request is not particularly invalid, I suppose adding it wouldn't change much about your internal thought process leading to your behaviour.

Thanks for your judgement and unsolicited advice. You don't know anything about my background, how adverse it is or is it situational or not. How can you pass off judgement like that. Try to have a little positive outlook towards things.

> If you truly want to get off the problem, you need to make your brain understand how YouTube is actually a huge pile of shit. Once you get that, you will stop having the urge to get sucked into the brainwashing machine YouTube is & you will neither need any challenge, nor force yourself to not look at suggestions, because you simply won't want to, in the first place.
> 
> If you are truly interested in fixing the root of the issue, I suggest you research how YouTube works, what it does, what the point of it is and, most importantly, how it evolved backward in the past 15 years.

Man you don't have the slightest idea about what you are talking about. That's like saying a substance addicted person that if they want to get rid of the problem they should understand how a substance works inside the body and how it can harm the body. Don't you think majority of the people know that smarta**. But still they keep doing it. So, better stick to coding and leave the psychiatric advice to psychiatrists/experts.

**Comment by theAkito** [comment]
@bhavyaw 

Thank you for confirming what I said. Your reaction speaks volumes. 👍🏻

**Comment by lawrencehook** [comment]
@bhavyaw For what it's worth, there is currently an option to enable the "menu timer" under the Settings tab. It forces you to wait 10 seconds before you're able to toggle any of the options.
